### ISSUE TITLE
Blog is Down

### ISSUE THREAD

**Issue by IanVS** [markkolich/blog#4]
I have a Krups KM7000 experiencing the same issues that yours had, and your blog post is one of the top on DuckDuckGo, but http://mark.koli.ch/ appears to be down.  Thanks for hosting the content on GitHub, as I was able to get just the info I needed.  Cheers!

**Comment by markkolich** [comment]
@IanVS sorry for inconvenience &mdash; I'm moving and my "home datacenter" has been offline for a few days.  Will be back online soon.  Glad you were able to get the details you needed.
